### ISSUE TITLE
Consolidate information

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#10]
The website should ideally act as the single source of truth for FAQ and other similar information.

- [x] https://github.com/inorichi/tachiyomi/wiki
- [x] https://github.com/tachiyomiorg/website/wiki/FAQ
- [x] Discord FAQ

**Comment by alessandrojean** [comment]
I can help with that if you guys need it, such as starting to complement the FAQ.

**Comment by arkon** [comment]
Sure, just make sure to post what you'll be working on so others don't end up doing the same thing

**Comment by alessandrojean** [comment]
Okay. I will start to complement the website FAQ with the other questions from this repo's wiki. Since they are categorized by sections (Application and Extensions) and their subcategories, I will see if I can split the FAQ in a file for the app questions and another one for the extension questions.

**Comment by arkon** [comment]
That actually related to another thing suggested on Discord, which I've logged as #11.

Not sure if you're on Discord and looking at the discussion in the #dev-website channel.

**Comment by alessandrojean** [comment]
The link on the issue it's exactly what I have in mind, separate the questions into categories. I will start only separating the existing questions for now.

**Comment by specterflare** [comment]
So I don't know if you want to close this issue or not, but the checklist is complete now.
