### ISSUE TITLE
Document more common library update errors

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#808]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

We should add to https://tachiyomi.org/help/guides/troubleshooting/#what-are-some-common-errors

...with more common things that we see nowadays such as:

- timeout
- connection reset
- SSL handshake aborted (e.g. https://cdn.discordapp.com/attachments/349436576037732355/924317756621455411/20211225_181042.jpg)
- Unable to resolve host (e.g. https://cdn.discordapp.com/attachments/349436576037732355/924265447996674118/IMG_20211225_121712.jpg)
- failed to connect to (e.g. https://cdn.discordapp.com/attachments/349436576037732355/924194749425020928/IMG_20211225_145916.jpg)
- not really an update error, but slow connections
- ...and I forget if there's anything else that commonly shows up in #support

We can link to this from the app to avoid some people going straight to Discord to ask what to do.

**Comment by curche** [comment]
From the current [What are some common errors](https://tachiyomi.org/help/guides/troubleshooting/#what-are-some-common-errors), I have listed out their present state:
| Common Error | Present State | Action |
|---------------------|--------------------|----------|
| Java.lang Exception: Challenge not found | no reports recently | can remove |
| Loader not implemented | " | can remove |
| Java.lang Exception: Failed to bypass Cloudflare | Very common but sometimes unsolvable | Stay; Cloudflare guide can be updated to include a note to the Cloudflare looping due to raised protection level (often by Scanlator websites) and that there isn't anything to do about it (except wait/migrate) |
| HTTP error 403 | " | " |
| " 429 | Sometimes | Stay; Reporting the extension to github would be good so that the extension can have ratelimits |
| " 5xx | Common | Stay |
| Unable to resolve host / Connection failed | Common | " |
| Chain validation failed | Sometimes | " |
| App not installed | Not Common | best to migrate/refer to the ["Unable to install the app or extensions"](https://tachiyomi.org/help/guides/troubleshooting/#unable-to-install-the-app-or-extensions) section with a note on F-Droid |
| Attempt to install virtual method hippo | Often | Stay |
| Cannot access SD Card | Sometimes | Stay; Sometimes changing to and back the location of sdcard and force closing the app helps |
| Storage issues with Android 11 | Sometimes | Stay; kinda very long section maybe have a section (like [Cloudflare](https://tachiyomi.org/help/guides/troubleshooting/#unable-to-install-the-app-or-extensions)) and point to that? |


### Other notes:
- `If error-specific instructions didn't help or your error isn't on the list, go through Diagnosis.` - shouldn't this be put at the bottom (of the common problems section) rather than the top? I feel that'd be better
- `The Preview version may have already fixed your issue. Just wait for a new Stable release.` - most of the problems are nowadays for the extension so this kinda feels at the wrong place. Might be just me.
- Semantics: The Cloudflare looping section would actually be a better as a sub-section to Cloudflare section
- The screenshot in [Crash logs section](https://tachiyomi.org/help/guides/troubleshooting/#getting-logcats-and-crash-logs) is old now. Crash logs sometimes contain nothing except for device specs in which case trying again helps to show better logs
- Although this isn't a library update error, it should be noted that long strip webtoons crashing the app has become more common (mostly since a lot of ppl use tachi to read long strip also now, more so on normal/budget devices). Could add it for the time being since the webtoon split feature isn't a thing yet.
- If we're linking it within the app, perhaps it might be good idea to have a look at the tachiyomi status-update webpage once again
